language: cpp
compiler:
  - gcc
before_install: |
  sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12
  if [[ "$CXX" == "g++" ]]; then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  fi
  sudo apt-get update -qq
install: |
  sudo apt-get install cmake
  if [[ "$CXX" == "g++" ]]; then
    sudo apt-get install -qq g++-4.8
  fi
  if [[ "$CXX" == "g++" ]]; then
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  fi
  sudo apt-get install flex libfl-dev nasm openssl libtecla1-dev libx11-dev
script: |
  mkdir -p build
  cd build
  cmake ..
  make
after_success:
  - make test
os:
  - linux
