language: cpp
jobs:
    include:
        - os: linux
          dist: bionic
        - os: linux
          dist: xenial
        - os: linux
          dist: trusty
compiler:
  - gcc
install: |
  sudo apt-get -y install nasm openssl libx11-dev
script: |
  mkdir -p build/dist
  cd build
  cmake ..
  if [ -r /proc/cpuinfo ]; then
    JOBS=$(grep -c processor /proc/cpuinfo)
  fi
  if [ ${JOBS:-0} -eq 0 ]; then
    JOBS=1
  fi
  make -j${JOBS}
  make test
  DESTDIR=$(pwd)/dist make install
