language: cpp
jobs:
    include:
        - os: linux
          dist: bionic
        - os: linux
          dist: xenial
        - os: linux
          dist: trusty
compiler:
  - gcc
install: |
  sudo apt-get -y install nasm openssl libx11-dev
script: |
  mkdir -p build/dist
  cd build
  cmake ..
  make
  make test
  DESTDIR=$(pwd)/dist make install
